# redis configuration
redis:
  db: 2
  addr: 10.7.178.38:6020
#  addr: 123.58.213.158:6020
  password: iphone5C,.

# email configuration
email:
  to: 'xxx@qq.com'
  port: 465
  from: 'xxx@163.com'
  host: 'smtp.163.com'
  is-ssl: true
  secret: 'xxx'
  nickname: 'test'

# system configuration
system:
  env: 'public'  # Change to "develop" to skip authentication for development mode
  addr: 8010
  db-type: 'mysql'
  oss-type: 'local'    # 控制oss选择走本期还是 七牛等其他仓 自行增加其他oss仓可以在 server/utils/upload/upload.go 中 NewOss函数配置
  use-multipoint: false
  # IP限制次数 一个小时15000次
  iplimit-count: 15000
  #  IP限制一个小时
  iplimit-time: 3600

# captcha configuration
captcha:
  key-long: 6
  img-width: 240
  img-height: 80

# mysql connect configuration
mysql:
  path: 172.17.0.1
#  port: 3306
#  path: 123.58.213.158
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: bankroll_way
  username: root
  password: iphone5C,.
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: error
  log-zap: ""

# local configuration
local:
  path: '/root/go/upload'

# excel configuration
excel:
  dir: '/root/go/upload'

# timer task db clear table
Timer:
  start: true
  spec: "@daily"  # 定时任务详细配置参考 https://pkg.go.dev/github.com/robfig/cron/v3
  detail: [
    # tableName: 需要清理的表名
    # compareField: 需要比较时间的字段
    # interval: 时间间隔, 具体配置详看 time.ParseDuration() 中字符串表示 且不能为负数
    # 2160h = 24 * 30 * 3 -> 三个月
    { tableName: "individual_bankroll" , compareField: "created_at", interval: "1440h" },
    { tableName: "individual_stock" , compareField: "created_at", interval: "1440h" },
    { tableName: "industry_bankroll" , compareField: "created_at", interval: "1440h" },
    { tableName: "plate_bankroll" , compareField: "created_at", interval: "1440h" },
    { tableName: "relat_dus_div" , compareField: "created_at", interval: "1440h" },
    { tableName: "stock_report" , compareField: "created_at", interval: "1440h" },
    { tableName: "bi_deal_detail" , compareField: "created_at", interval: "1440h" },
  ]

zap:
  level: error
  format: console
  prefix: '[]'
  director: log
  showLine: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
